$( document ).ready(function() {

    var availableAirports = [
        "369 - Atmautluak (Atmautluak Airport)",
        "04G - Youngstown (Lansdowne Airport)",
        "06A - Tuskegee (Moton Field Municipal Airport)",
        "06C - Schaumburg (Schaumburg Regional)",
        "06N - Middletown (Randall Airport)",
        "09J - Jekyll Island (Jekyll Island Airport)",
        "0A9 - Elizabethton (Elizabethton Municipal Airport)",
        "0G6 - Bryan (Williams County Airport)",
        "0G7 - Seneca Falls (Finger Lakes Regional Airport)",
        "0P2 - Stewartstown (Shoestring Aviation Airfield)",
        "0S9 - Port Townsend (Jefferson County Intl)",
        "0W3 - Churchville (Harford County Airport)",
        "10C - Greenwood (Galt Field Airport)",
        "17G - Bucyrus (Port Bucyrus-Crawford County Airport)",
        "19A - Jefferson (Jackson County Airport)",
        "1A3 - Copperhead (Martin Campbell Field Airport)",
        "1B9 - Mansfield (Mansfield Municipal)",
        "1CS - Bolingbrook (Clow International Airport)",
        "1G3 - Kent (Kent State Airport)",
        "1OH - St. Marys (Fortman Airport)",
        "1RL - Point Roberts (Point Roberts Airpark)",
        "24C - Lowell (Lowell City Airport)",
        "24J - Live Oak (Suwannee County Airport)",
        "25D - Forest Lake (Forest Lake Airport)",
        "29D - Grove City (Grove City Airport)",
        "2A0 - Dayton (Mark Anton Airport)",
        "2G2 - Steubenville (Jefferson County Airpark)",
        "2G9 - Somerset (Somerset County Airport)",
        "2J9 - Quincy (Quincy Municipal Airport)",
        "36U - Heber (Heber City Municipal Airport)",
        "38W - Lynden (Lynden Airport)",
        "3G3 - Wadsworth (Wadsworth Municipal)",
        "3G4 - Ashland (Ashland County Airport)",
        "3J1 - Ridgeland (Ridgeland Airport)",
        "3W2 - Put-in-Bay (Put-in-Bay Airport)",
        "40J - Perry (Perry-Foley Airport)",
        "41N - Braceville (Braceville Airport)",
        "47A - Canton (Cherokee County Airport)",
        "49A - Ellijay (Gilmer County Airport)",
        "49X - Chemehuevi Valley (Chemehuevi Valley)",
        "4A4 - Cedartown (Polk County Airport - Cornelius Moore Field)",
        "4A9 - Fort Payne (Isbell Field Airport)",
        "4B8 - Plainville (Robertson Field)",
        "4G0 - Monroeville (Pittsburgh-Monroeville Airport)",
        "4G2 - Hamburg (Hamburg Inc Airport)",
        "4G4 - Youngstown (Youngstown Elser Metro Airport)",
        "4I7 - Greencastle (Putnam County Airport)",
        "4U9 - Dell (Dell Flight Strip)",
        "52A - Madison (Madison GA Municipal Airport)",
        "54J - DeFuniak Springs (DeFuniak Springs Airport)",
        "55J - Fernandina Beach (Fernandina Beach Municipal Airport)",
        "57C - East Troy (East Troy Municipal Airport)",
        "60J - Ocean Isle Beach (Ocean Isle Beach Airport)",
        "6A2 - Griffin (Griffin-Spalding County Airport)",
        "6K8 - Tok (Tok Junction Airport)",
        "6S0 - Big Timber (Big Timber Airport)",
        "6S2 - Florence (Florence)",
        "6Y8 - Beaver Island (Welke Airport)",
        "70J - Cairo (Cairo-Grady County Airport)",
        "70N - Sterling (Spring Hill Airport)",
        "7A4 - Apple River (Foster Field)",
        "7D9 - Geneva (Germack Airport)",
        "7N7 - Pedricktown (Spitfire Aerodrome)",
        "8M8 - Lewiston (Garland Airport)",
        "93C - Richland Center (Richland Airport)",
        "99N - Bamberg (Bamberg County Airport)",
        "9A1 - Covington (Covington Municipal Airport)",
        "9A5 - LaFayette (Barwick Lafayette Airport)",
        "A39 - Phoenix (Phoenix Regional Airport)",
        "AAF - Apalachicola (Apalachicola Regional Airport)",
        "ABE - Allentown (Lehigh Valley Intl)",
        "ABI - Abilene (Abilene Rgnl)",
        "ABL - Ambler (Ambler Airport)",
        "ABQ - Albuquerque (Albuquerque International Sunport)",
        "ABR - Aberdeen (Aberdeen Regional Airport)",
        "ABY - Albany (Southwest Georgia Regional Airport)",
        "ACK - Nantucket (Nantucket Mem)",
        "ACT - Waco (Waco Rgnl)",
        "ACV - Arcata CA (Arcata)",
        "ACY - Atlantic City (Atlantic City Intl)",
        "ADK - Adak Island (Adak Airport)",
        "ADM - Ardmore (Ardmore Muni)",
        "ADQ - Kodiak (Kodiak)",
        "ADS - Addison (Addison)",
        "ADW - Camp Springs (Andrews Afb)",
        "AET - Allakaket (Allakaket Airport)",
        "AEX - Alexandria (Alexandria Intl)",
        "AFE - Kake (Kake Airport)",
        "AFW - Fort Worth (Fort Worth Alliance Airport)",
        "AGC - Pittsburgh (Allegheny County Airport)",
        "AGN - Angoon (Angoon Seaplane Base)",
        "AGS - Bush Field (Augusta Rgnl At Bush Fld)",
        "AHN - Athens (Athens Ben Epps Airport)",
        "AIA - Alliance (Alliance Municipal Airport)",
        "AIK - Aiken (Municipal Airport)",
        "AIN - Wainwright (Wainwright Airport)",
        "AIZ - Kaiser Lake Ozark (Lee C Fine Memorial Airport)",
        "AKB - Atka (Atka Airport)",
        "AKC - Akron (Akron Fulton Intl)",
        "AKI - Akiak (Akiak Airport)",
        "AKK - Akhiok (Akhiok Airport)",
        "AKN - King Salmon (King Salmon)",
        "AKP - Anaktuvuk Pass (Anaktuvuk Pass Airport)",
        "ALB - Albany (Albany Intl)",
        "ALI - Alice (Alice Intl)",
        "ALM - Alamogordo (Alamogordo White Sands Regional Airport)",
        "ALO - Waterloo (Waterloo Regional Airport)",
        "ALS - Alamosa (San Luis Valley Regional Airport)",
        "ALW - Walla Walla (Walla Walla Regional Airport)",
        "ALX - Alexandria (Alexandria)",
        "ALZ - Lazy Bay (Alitak Seaplane Base)",
        "AMA - Amarillo (Rick Husband Amarillo Intl)",
        "ANB - Anniston (Anniston Metro)",
        "ANC - Anchorage (Ted Stevens Anchorage Intl)",
        "AND - Andersen (Anderson Rgnl)",
        "ANI - Aniak (Aniak Airport)",
        "ANN - Annette Island (Annette Island)",
        "ANP - Annapolis (Lee Airport)",
        "ANQ - Angola (Tri-State Steuben County Airport)",
        "ANV - Anvik (Anvik Airport)",
        "AOH - Lima (Lima Allen County Airport)",
        "AOO - Altoona (Altoona Blair Co)",
        "AOS - Amook Bay (Amook Bay Seaplane Base)",
        "APA - Denver (Centennial)",
        "APC - Napa (Napa County Airport)",
        "APF - Naples (Naples Muni)",
        "APG - Aberdeen (Phillips Aaf)",
        "APN - Alpena (Alpena County Regional Airport)",
        "AQC - Klawock (Klawock Seaplane Base)",
        "ARA - Louisiana (Acadiana Rgnl)",
        "ARC - Arctic Village (Arctic Village Airport)",
        "ART - Watertown (Watertown Intl)",
        "ARV - Minocqua - Woodruff (Lakeland)",
        "ASE - Aspen (Aspen Pitkin County Sardy Field)",
        "ASH - Nashua (Boire Field Airport)",
        "AST - Astoria (Astoria Regional Airport)",
        "ATK - Atqasuk (Atqasuk Edward Burnell Sr Memorial Airport)",
        "ATL - Atlanta (Hartsfield Jackson Atlanta Intl)",
        "ATT - Austin TX (Camp Mabry Austin City)",
        "ATW - Appleton (Appleton)",
        "ATY - Watertown (Watertown Regional Airport)",
        "AUG - Augusta (Augusta State)",
        "AUK - Alakanuk (Alakanuk Airport)",
        "AUS - Austin (Austin Bergstrom Intl)",
        "AUW - Wausau (Wausau Downtown Airport)",
        "AVL - Asheville (Asheville Regional Airport)",
        "AVO - Avon Park (Executive)",
        "AVP - Scranton (Wilkes Barre Scranton Intl)",
        "AVW - Tucson (Marana Regional)",
        "AVX - Catalina Island (Avalon)",
        "AZA - Mesa (Phoenix-Mesa Gateway)",
        "AZO - Kalamazoo (Kalamazoo)",
        "BAB - Marysville (Beale Afb)",
        "BAD - Shreveport (Barksdale Afb)",
        "BAF - Westfield (Barnes Municipal)",
        "BBX - Philadelphia (Wings Field)",
        "BCE - Bryce Canyon (Bryce Canyon)",
        "BCT - Boca Raton (Boca Raton)",
        "BDE - Baudette (Baudette Intl)",
        "BDL - Windsor Locks (Bradley Intl)",
        "BDR - Stratford (Igor I Sikorsky Mem)",
        "BEC - Wichita (Beech Factory Airport)",
        "BED - Bedford (Laurence G Hanscom Fld)",
        "BEH - Benton Harbor (Southwest Michigan Regional Airport)",
        "BET - Bethel (Bethel)",
        "BFD - Bradford (Bradford Regional Airport)",
        "BFF - Scottsbluff (Western Nebraska Regional Airport)",
        "BFI - Seattle (Boeing Fld King Co Intl)",
        "BFL - Bakersfield (Meadows Fld)",
        "BFM - Mobile (Mobile Downtown)",
        "BFP - Beaver Falls (Beaver Falls)",
        "BFT - Beaufort (Beaufort)",
        "BFT - Beauford (BFT County Airport)",
        "BGE - Bainbridge (Decatur County Industrial Air Park)",
        "BGM - Binghamton (Greater Binghamton Edwin A Link Fld)",
        "BGR - Bangor (Bangor Intl)",
        "BHB - Bar Harbor (Hancock County - Bar Harbor)",
        "BHM - Birmingham (Birmingham Intl)",
        "BID - Block Island (Block Island State Airport)",
        "BIF - El Paso (Biggs Aaf)",
        "BIG - Delta Junction (Allen Aaf)",
        "BIL - Billings (Billings Logan International Airport)",
        "BIS - Bismarck (Bismarck Municipal Airport)",
        "BIV - Holland (Tulip City Airport)",
        "BIX - Biloxi (Keesler Afb)",
        "BJC - Broomfield-CO (Rocky Mountain Metropolitan Airport)",
        "BJI - Bemidji (Bemidji Regional Airport)",
        "BKC - Buckland (Buckland Airport)",
        "BKD - Breckenridge (Stephens Co)",
        "BKF - Buckley (Buckley Afb)",
        "BKG - Branson (Branson LLC)",
        "BKH - Barking Sands (Barking Sands Pmrf)",
        "BKL - Cleveland (Burke Lakefront Airport)",
        "BKW - Beckley (Raleigh County Memorial Airport)",
        "BKX - Brookings (Brookings Regional Airport)",
        "BLD - Boulder City (Boulder City Municipal Airport)",
        "BLF - Bluefield (Mercer County Airport)",
        "BLH - Blythe (Blythe Airport)",
        "BLI - Bellingham (Bellingham Intl)",
        "BLV - Belleville (Scott Afb Midamerica)",
        "BMC - Brigham City (Brigham City)",
        "BMG - Bloomington (Monroe County Airport)",
        "BMI - Bloomington (Central Illinois Rgnl)",
        "BMX - Big Mountain (Big Mountain Afs)",
        "BNA - Nashville (Nashville Intl)",
        "BOI - Boise (Boise Air Terminal)",
        "BOS - Boston (General Edward Lawrence Logan Intl)",
        "BOW - Bartow (Bartow Municipal Airport)",
        "BPT - Beaumont (Southeast Texas Rgnl)",
        "BQK - Brunswick (Brunswick Golden Isles Airport)",
        "BRD - Brainerd (Brainerd Lakes Rgnl)",
        "BRL - Burlington (Southeast Iowa Regional Airport)",
        "BRO - Brownsville (Brownsville South Padre Island Intl)",
        "BRW - Barrow (Wiley Post Will Rogers Mem)",
        "BSF - Bradshaw Field (Bradshaw Aaf)",
        "BTI - Barter Island (Barter Island Lrrs)",
        "BTM - Butte (Bert Mooney Airport)",
        "BTR - Baton Rouge (Baton Rouge Metro Ryan Fld)",
        "BTT - Bettles (Bettles)",
        "BTV - Burlington (Burlington Intl)",
        "BUF - Buffalo (Buffalo Niagara Intl)",
        "BUR - Burbank (Bob Hope)",
        "BUU - Burlington (Municipal Airport)",
        "BUY - Burlington (Burlington-Alamance Regional Airport)",
        "BVY - Beverly (Beverly Municipal Airport)",
        "BWD - Brownwood (KBWD)",
        "BWG - Bowling Green (Bowling Green-Warren County Regional Airport)",
        "BWI - Baltimore (Baltimore Washington Intl)",
        "BXK - Buckeye (Buckeye Municipal Airport)",
        "BXS - Borrego Springs (Borrego Valley Airport)",
        "BYH - Blytheville (Arkansas Intl)",
        "BYS - Fort Irwin (Bicycle Lake Aaf)",
        "BYW - Blakely Island (Blakely Island Airport)",
        "BZN - Bozeman (Gallatin Field)",
        "C02 - Lake Geneva (Grand Geneva Resort Airport)",
        "C16 - Urbana (Frasca Field)",
        "C47 - Portage (Portage Municipal Airport)",
        "C65 - Plymouth (Plymouth Municipal Airport)",
        "C89 - Sturtevant (Sylvania Airport)",
        "C91 - Dowagiac (Dowagiac Municipal Airport)",
        "CAE - Columbia (Columbia Metropolitan)",
        "CAK - Akron (Akron Canton Regional Airport)",
        "CAR - Caribou (Caribou Muni)",
        "CBE - Cumberland (Greater Cumberland Rgnl.)",
        "CBM - Colombus (Columbus Afb)",
        "CCO - Newnan (Coweta County Airport)",
        "CCR - Concord (Buchanan Field Airport)",
        "CDB - Cold Bay (Cold Bay)",
        "CDC - Cedar City (Cedar City Rgnl)",
        "CDI - Cambridge (Cambridge Municipal Airport)",
        "CDK - Cedar Key (CedarKey)",
        "CDN - Camden (Woodward Field)",
        "CDR - Chadron (Chadron Municipal Airport)",
        "CDS - Childress (Childress Muni)",
        "CDV - Cordova (Merle K Mudhole Smith)",
        "CDW - Caldwell (Caldwell Essex County Airport)",
        "CEC - Crescent City (Del Norte County Airport)",
        "CEF - Chicopee Falls (Westover Arb Metropolitan)",
        "CEM - Central (Central Airport)",
        "CEU - Clemson (Clemson)",
        "CEW - Crestview (Bob Sikes)",
        "CEZ - Cortez (Cortez Muni)",
        "CFD - Bryan (Coulter Fld)",
        "CGA - Craig (Craig Seaplane Base)",
        "CGF - Richmond Heights (Cuyahoga County)",
        "CGI - Cape Girardeau (Cape Girardeau Regional Airport)",
        "CGX - Chicago (Meigs Field)",
        "CGZ - Casa Grande (Casa Grande Municipal Airport)",
        "CHA - Chattanooga (Lovell Fld)",
        "CHI - Chicago (All Airports)",
        "CHO - Charlottesville VA (Charlottesville-Albemarle)",
        "CHS - Charleston (Charleston Afb Intl)",
        "CHU - Chuathbaluk (Chuathbaluk Airport)",
        "CIC - Chico (Chico Muni)",
        "CID - Cedar Rapids (Cedar Rapids)",
        "CIK - Chalkyitsik (Chalkyitsik Airport)",
        "CIL - Council (Council Airport)",
        "CIU - Sault Ste Marie (Chippewa County International Airport)",
        "CKB - Clarksburg (Harrison Marion Regional Airport)",
        "CKD - Crooked Creek (Crooked Creek Airport)",
        "CKF - Cordele (Crisp County Cordele Airport)",
        "CKV - Clarksville (Clarksville-Montgomery County Regional Airport)",
        "CLC - Clear Lake City (Clear Lake Metroport)",
        "CLD - Carlsbad (McClellan-Palomar Airport)",
        "CLE - Cleveland (Cleveland Hopkins Intl)",
        "CLL - College Station (Easterwood Fld)",
        "CLM - Port Angeles (William R Fairchild International Airport)",
        "CLT - Charlotte (Charlotte Douglas Intl)",
        "CLW - Clearwater (Clearwater Air Park)",
        "CMH - Columbus (Port Columbus Intl)",
        "CMI - Champaign (Champaign)",
        "CMX - Hancock (Houghton County Memorial Airport)",
        "CNM - Carlsbad (Cavern City Air Terminal)",
        "CNW - Waco (Tstc Waco)",
        "CNY - Moab (Canyonlands Field)",
        "COD - Cody (Yellowstone Rgnl)",
        "COF - Coco Beach (Patrick Afb)",
        "CON - Concord NH (Concord Municipal)",
        "COS - Colorado Springs (City Of Colorado Springs Muni)",
        "COT - Cotulla (Cotulla Lasalle Co)",
        "COU - Columbia (Columbia Rgnl)",
        "CPR - Casper (Natrona Co Intl)",
        "CPS - East St. Louis (St. Louis Downtown Airport)",
        "CRE - North Myrtle Beach (Grand Strand Airport)",
        "CRP - Corpus Christi (Corpus Christi Intl)",
        "CRW - Charleston (Yeager)",
        "CSG - Columbus (Columbus Metropolitan Airport)",
        "CTB - Cutbank (Cut Bank Muni)",
        "CTH - Coatesville (Chester County G O Carlson Airport)",
        "CTJ - Carrollton (West Georgia Regional Airport - O V Gray Field)",
        "CTY - Cross City (Cross City)",
        "CVG - Cincinnati (Cincinnati Northern Kentucky Intl)",
        "CVN - Clovis (Clovis Muni)",
        "CVS - Clovis (Cannon Afb)",
        "CVX - Charelvoix (Charlevoix Municipal Airport)",
        "CWA - Wassau (Central Wisconsin)",
        "CWI - Clinton (Clinton Municipal)",
        "CXF - Coldfoot (Coldfoot Airport)",
        "CXL - Calexico (Calexico Intl)",
        "CXO - Conroe (Lone Star Executive)",
        "CXY - Harrisburg (Capital City Airport)",
        "CYF - Chefornak (Chefornak Airport)",
        "CYM - Sitka (Chatham Seaplane Base)",
        "CYS - Cheyenne (Cheyenne Rgnl Jerry Olson Fld)",
        "CYT - Yakataga (Yakataga Airport)",
        "CZF - Cape Romanzof (Cape Romanzof Lrrs)",
        "CZN - Chisana (Chisana Airport)",
        "DAB - Daytona Beach (Daytona Beach Intl)",
        "DAL - Dallas (Dallas Love Fld)",
        "DAY - Dayton (James M Cox Dayton Intl)",
        "DBQ - Dubuque IA (Dubuque Rgnl)",
        "DCA - Washington (Ronald Reagan Washington Natl)",
        "DDC - Dodge City (Dodge City Regional Airport)",
        "DEC - Decatur (Decatur)",
        "DEN - Denver (Denver Intl)",
        "DET - Detroit (Coleman A Young Muni)",
        "DFW - Dallas-Fort Worth (Dallas Fort Worth Intl)",
        "DGL - Douglas (Douglas Municipal Airport)",
        "DHN - Dothan (Dothan Rgnl)",
        "DHT - Dalhart (Dalhart Muni)",
        "DIK - Dickinson (Dickinson Theodore Roosevelt Regional Airport)",
        "DKB - De Kalb (De Kalb Taylor Municipal Airport)",
        "DKK - Dunkirk (Chautauqua County-Dunkirk Airport)",
        "DKX - Knoxville (Knoxville Downtown Island Airport)",
        "DLF - Del Rio (Laughlin Afb)",
        "DLG - Dillingham (Dillingham)",
        "DLH - Duluth (Duluth Intl)",
        "DLL - Baraboo (Baraboo Wisconsin Dells Airport)",
        "DMA - Tucson (Davis Monthan Afb)",
        "DNL - Augusta (Daniel Field Airport)",
        "DNN - Dalton (Dalton Municipal Airport)",
        "DOV - Dover (Dover Afb)",
        "DPA - West Chicago (Dupage)",
        "DQH - Douglas (Douglas Municipal Airport)",
        "DRG - Deering (Deering Airport)",
        "DRI - Deridder (Beauregard Rgnl)",
        "DRM - Drummond Island (Drummond Island Airport)",
        "DRO - Durango (Durango La Plata Co)",
        "DRT - Del Rio (Del Rio Intl)",
        "DSM - Des Moines (Des Moines Intl)",
        "DTA - Delta (Delta Municipal Airport)",
        "DTS - Destin (Destin)",
        "DTW - Detroit (Detroit Metro Wayne Co)",
        "DUC - Duncan (Halliburton Field Airport)",
        "DUG - Douglas (Bisbee Douglas Intl)",
        "DUJ - Du Bois (DuBois Regional Airport)",
        "DUT - Unalaska (Unalaska)",
        "DVL - Devils Lake (Devils Lake Regional Airport)",
        "DVT - Phoenix  (Deer Valley Municipal Airport)",
        "DWA - Davis-Woodland-Winters (Yolo County Airport)",
        "DWH - Houston (David Wayne Hooks Field)",
        "DWS - Orlando (Orlando)",
        "DXR - Danbury (Danbury Municipal Airport)",
        "DYS - Abilene (Dyess Afb)",
        "E25 - Wickenburg (Wickenburg Municipal Airport)",
        "E51 - Bagdad (Bagdad Airport)",
        "E55 - Gualala (Ocean Ridge Airport)",
        "E63 - Gila Bend (Gila Bend Municipal Airport)",
        "E91 - Chinle (Chinle Municipal Airport)",
        "EAA - Eagle (Eagle Airport)",
        "EAR - Kearney (Kearney Municipal Airport)",
        "EAT - Wenatchee (Pangborn Field)",
        "EAU - Eau Claire (Chippewa Valley Regional Airport)",
        "ECA - East Tawas (Iosco County)",
        "ECG - Elizabeth City (Elizabeth City Cgas Rgnl)",
        "ECP - Panama City (Panama City-NW Florida Bea.)",
        "EDF - Anchorage (Elmendorf Afb)",
        "EDW - Edwards Afb (Edwards Afb)",
        "EEK - Eek (Eek Airport)",
        "EEN - Keene (Dillant Hopkins Airport)",
        "EET - Alabaster (Shelby County Airport)",
        "EFD - Houston (Ellington Fld)",
        "EGA - Eagle (Eagle County Airport)",
        "EGE - Vail (Eagle Co Rgnl)",
        "EGT - Wellington (Wellington Municipal)",
        "EGV - Eagle River (Eagle River)",
        "EGX - Egegik (Egegik Airport)",
        "EHM - Cape Newenham (Cape Newenham Lrrs)",
        "EIL - Fairbanks (Eielson Afb)",
        "EKN - Elkins (Elkins Randolph Co Jennings Randolph)",
        "EKO - Elko (Elko Regional Airport)",
        "ELD - El Dorado (South Arkansas Rgnl At Goodwin Fld)",
        "ELI - Elim (Elim Airport)",
        "ELM - Elmira (Elmira Corning Rgnl)",
        "ELP - El Paso (El Paso Intl)",
        "ELV - Elfin Cove (Elfin Cove Seaplane Base)",
        "ELY - Ely (Ely Airport)",
        "EMK - Emmonak (Emmonak Airport)",
        "EMP - Emporia (Emporia Municipal Airport)",
        "ENA - Kenai (Kenai Muni)",
        "END - Enid (Vance Afb)",
        "ENV - Wendover (Wendover)",
        "ENW - Kenosha (Kenosha Regional Airport)",
        "EOK - Keokuk (Keokuk Municipal Airport)",
        "EPM - Eastport (Eastport Municipal Airport)",
        "EQY - Charlotte (Monroe Reqional Airport)",
        "ERI - Erie (Erie Intl Tom Ridge Fld)",
        "ERV - Kerrville (Kerrville Municipal Airport)",
        "ERY - Newberry (Luce County Airport)",
        "ESC - Escanaba (Delta County Airport)",
        "ESD - Eastsound (Orcas Island Airport)",
        "ESF - Alexandria (Esler Rgnl)",
        "ESN - Easton (Easton-Newnam Field Airport)",
        "EUG - Eugene (Mahlon Sweet Fld)",
        "EVV - Evansville (Evansville Regional)",
        "EWB - New Bedford (New Bedford Regional Airport)",
        "EWN - New Bern (Craven Co Rgnl)",
        "EWR - Newark (Newark Liberty Intl)",
        "EXI - Excursion Inlet (Excursion Inlet Seaplane Base)",
        "EYW - Key West (Key West Intl)",
        "F57 - Winterhaven (Seaplane Base)",
        "FAF - Fort Eustis (Felker Aaf)",
        "FAI - Fairbanks (Fairbanks Intl)",
        "FAR - Fargo (Hector International Airport)",
        "FAT - Fresno (Fresno Yosemite Intl)",
        "FAY - Fayetteville (Fayetteville Regional Grannis Field)",
        "FBG - Fredericksburg (Fredericksburg Amtrak Station)",
        "FBK - Fort Wainwright (Ladd Aaf)",
        "FBS - Friday Harbor (Friday Harbor Seaplane Base)",
        "FCA - Kalispell (Glacier Park Intl)",
        "FCS - Fort Carson (Butts Aaf)",
        "FDY - Findley (Findlay Airport)",
        "FFA - Kill Devil Hills (First Flight Airport)",
        "FFC - Atlanta (Atlanta Regional Airport - Falcon Field)",
        "FFO - Dayton (Wright Patterson Afb)",
        "FFT - Frankfort (Capital City Airport)",
        "FFZ - Mesa (Mesa Falcon Field)",
        "FHU - Fort Huachuca (Sierra Vista Muni Libby Aaf)",
        "FIT - Fitchburg (Fitchburg Municipal Airport)",
        "FKL - Franklin (Franklin)",
        "FLD - Fond du Lac (Fond Du Lac County Airport)",
        "FLG - Flagstaff (Flagstaff Pulliam Airport)",
        "FLL - Fort Lauderdale (Fort Lauderdale Hollywood Intl)",
        "FLO - Florence (Florence Rgnl)",
        "FLV - Fort Leavenworth (Sherman Aaf)",
        "FME - Fort Meade (Tipton)",
        "FMH - Falmouth (Otis Angb)",
        "FMN - Farmington (Four Corners Rgnl)",
        "FMY - Fort Myers (Page Fld)",
        "FNL - Fort Collins (Fort Collins Loveland Muni)",
        "FNR - Funter Bay (Funter Bay Seaplane Base)",
        "FNT - Flint (Bishop International)",
        "FOD - Fort Dodge (Fort Dodge Rgnl)",
        "FOE - Topeka (Forbes Fld)",
        "FOK - West Hampton Beach (Francis S Gabreski)",
        "FRD - Friday Harbor (Friday Harbor Airport)",
        "FRI - Fort Riley (Marshall Aaf)",
        "FRN - Fort Richardson (Bryant Ahp)",
        "FRP - Fort Pierce (St Lucie County International Airport)",
        "FSD - Sioux Falls (Sioux Falls)",
        "FSI - Fort Sill (Henry Post Aaf)",
        "FSM - Fort Smith (Fort Smith Rgnl)",
        "FST - Fort Stockton (Fort Stockton Pecos Co)",
        "FTK - Fort Knox (Godman Aaf)",
        "FTW - Fort Worth (Fort Worth Meacham Intl)",
        "FTY - Atlanta (Fulton County Airport Brown Field)",
        "FUL - Fullerton (Fullerton Municipal Airport)",
        "FWA - Fort Wayne (Fort Wayne)",
        "FXE - Fort Lauderdale (Fort Lauderdale Executive)",
        "FYU - Fort Yukon (Fort Yukon)",
        "FYV - Fayetteville (Drake Fld)",
        "FZG - Fitzgerald (Fitzgerald Municipal Airport)",
        "GAD - Gadsden (Northeast Alabama Regional Airport)",
        "GAI - Gaithersburg (Montgomery County Airpark)",
        "GAL - Galena (Edward G Pitka Sr)",
        "GAM - Gambell (Gambell Airport)",
        "GBN - Great Bend (Great Bend Municipal)",
        "GCC - Gillette (Gillette-Campbell County Airport)",
        "GCK - Garden City (Garden City Rgnl)",
        "GCN - Grand Canyon (Grand Canyon National Park Airport)",
        "GCW - Grand Canyon West (Grand Canyon West Airport)",
        "GDV - Glendive (Dawson Community Airport)",
        "GDW - Gladwin (Gladwin Zettel Memorial Airport)",
        "GED - Georgetown (Sussex Co)",
        "GEG - Spokane (Spokane Intl)",
        "GFK - Grand Forks (Grand Forks Intl)",
        "GGE - Georgetown (Georgetown County Airport)",
        "GGG - Longview (East Texas Rgnl)",
        "GGW - Glasgow (Wokal Field Glasgow International Airport)",
        "GHG - Marshfield (Marshfield Municipal Airport)",
        "GIF - Winter Haven (Gilbert Airport)",
        "GJT - Grand Junction (Grand Junction Regional)",
        "GKN - Gulkana (Gulkana)",
        "GKY - Arlington (Arlington Municipal)",
        "GLD - Goodland (Renner Fld)",
        "GLH - Greenville (Mid Delta Regional Airport)",
        "GLS - Galveston (Scholes Intl At Galveston)",
        "GLV - Golovin (Golovin Airport)",
        "GNT - Grants (Grants Milan Muni)",
        "GNU - Goodnews Bay (Goodnews Airport)",
        "GNV - Gainesville (Gainesville Rgnl)",
        "GON - Groton CT (Groton New London)",
        "GPT - Gulfport (Gulfport-Biloxi)",
        "GPZ - Grand Rapids MN (Grand Rapids Itasca County)",
        "GQQ - Galion (Galion Municipal Airport)",
        "GRB - Green Bay (Austin Straubel Intl)",
        "GRF - Fort Lewis (Gray Aaf)",
        "GRI - Grand Island (Central Nebraska Regional Airport)",
        "GRK - Killeen (Robert Gray Aaf)",
        "GRM - Grand Marais (Grand Marais Cook County Airport)",
        "GRR - Grand Rapids (Gerald R Ford Intl)",
        "GSB - Goldsboro (Seymour Johnson Afb)",
        "GSO - Greensboro (Piedmont Triad)",
        "GSP - Greenville (Greenville-Spartanburg International)",
        "GST - Gustavus (Gustavus Airport)",
        "GTB - Fort Drum (Wheeler Sack Aaf)",
        "GTF - Great Falls (Great Falls Intl)",
        "GTR - Columbus Mississippi (Golden Triangle Regional Airport)",
        "GTU - Georgetown (Georgetown Municipal Airport)",
        "GUC - Gunnison (Gunnison - Crested Butte)",
        "GUP - Gallup (Gallup Muni)",
        "GUS - Peru (Grissom Arb)",
        "GVL - Gainesville (Lee Gilmer Memorial Airport)",
        "GVQ - Batavia (Genesee County Airport)",
        "GVT - Greenvile (Majors)",
        "GWO - Greenwood (Greenwood Leflore)",
        "GYY - Gary (Gary Chicago International Airport)",
        "HBG - Hattiesburg (Hattiesburg Bobby L. Chain Municipal Airport)",
        "HBR - Hobart (Hobart Muni)",
        "HCC - Hudson NY (Columbia County)",
        "HCR - Holy Cross (Holy Cross Airport)",
        "HDH - Dillingham (Dillingham)",
        "HDI - Cleveland (Hardwick Field Airport)",
        "HDN - Hayden (Yampa Valley)",
        "HDO - Hondo (Hondo Municipal Airport)",
        "HFD - Hartford (Hartford Brainard)",
        "HGR - Hagerstown (Hagerstown Regional Richard A Henson Field)",
        "HHH - Hilton Head (Hilton Head)",
        "HHI - Wahiawa (Wheeler Aaf)",
        "HHR - Hawthorne (Jack Northrop Fld Hawthorne Muni)",
        "HIB - Hibbing (Chisholm Hibbing)",
        "HIF - Ogden (Hill Afb)",
        "HII - Lake Havasu City (Lake Havasu City Airport)",
        "HIO - Hillsboro (Portland Hillsboro)",
        "HKB - Healy (Healy River Airport)",
        "HKY - Hickory (Hickory Rgnl)",
        "HLG - Wheeling (Wheeling Ohio County Airport)",
        "HLN - Helena (Helena Rgnl)",
        "HLR - Fort Hood (Hood Aaf)",
        "HMN - Alamogordo (Holloman Afb)",
        "HNH - Hoonah (Hoonah Airport)",
        "HNL - Honolulu (Honolulu Intl)",
        "HNM - Hana (Hana)",
        "HNS - Haines (Haines Airport)",
        "HOB - Hobbs (Lea Co Rgnl)",
        "HOM - Homer (Homer)",
        "HON - Huron (Huron Rgnl)",
        "HOP - Hopkinsville (Campbell Aaf)",
        "HOT - Hot Springs (Memorial Field)",
        "HOU - Houston (William P Hobby)",
        "HPB - Hooper Bay (Hooper Bay Airport)",
        "HPN - White Plains (Westchester Co)",
        "HQM - Hoquiam (Bowerman Field)",
        "HQU - Thomson (McDuffie County Airport)",
        "HRL - Harlingen (Valley Intl)",
        "HRO - Harrison (Boone Co)",
        "HRT - Mary Esther (Hurlburt Fld)",
        "HSH - Henderson (Henderson Executive Airport)",
        "HSL - Huslia (Huslia Airport)",
        "HST - Homestead (Homestead Arb)",
        "HSV - Huntsville (Huntsville International Airport-Carl T Jones Field)",
        "HTL - Houghton Lake (Roscommon Co)",
        "HTS - Huntington (Tri State Milton J Ferguson Field)",
        "HUA - Redstone (Redstone Aaf)",
        "HUF - Terre Haute (Terre Haute Intl Hulman Fld)",
        "HUL - Houlton (Houlton Intl)",
        "HUS - Hughes (Hughes Airport)",
        "HUT - Hutchinson (Hutchinson Municipal Airport)",
        "HVN - New Haven (Tweed-New Haven Airport)",
        "HVR - Havre (Havre City Co)",
        "HWO - Hollywood (North Perry)",
        "HXD - Hilton Head Island (Hilton Head Airport)",
        "HYA - Barnstable (Barnstable Muni Boardman Polando Fld)",
        "HYG - Hydaburg (Hydaburg Seaplane Base)",
        "HYL - Hollis (Hollis Seaplane Base)",
        "HYS - Hays (Hays Regional Airport)",
        "HZL - Hazleton (Hazleton Municipal)",
        "IAB - Wichita (Mc Connell Afb)",
        "IAD - Washington (Washington Dulles Intl)",
        "IAG - Niagara Falls (Niagara Falls Intl)",
        "IAH - Houston (George Bush Intercontinental)",
        "IAN - Kiana (Bob Baker Memorial Airport)",
        "ICT - Wichita (Wichita Mid Continent)",
        "ICY - Icy Bay (Icy Bay Airport)",
        "IDA - Idaho Falls (Idaho Falls Rgnl)",
        "IDL - New York (Idlewild Intl)",
        "IFP - Bullhead (Laughlin-Bullhead Intl)",
        "IGG - Igiugig (Igiugig Airport)",
        "IGM - Kingman (Kingman Airport)",
        "IGQ - Lansing (Lansing Municipal)",
        "IJD - Willimantic (Windham Airport)",
        "IKK - Kankakee (Greater Kankakee)",
        "IKO - Nikolski (Nikolski Air Station)",
        "IKR - Kirtland A.f.b. (Kirtland Air Force Base)",
        "IKV - Ankeny (Ankeny Regl Airport)",
        "ILG - Wilmington (New Castle)",
        "ILI - Iliamna (Iliamna)",
        "ILM - Wilmington (Wilmington Intl)",
        "ILN - Wilmington (Wilmington Airborne Airpark)",
        "IMT - Iron Mountain (Ford Airport)",
        "IND - Indianapolis (Indianapolis Intl)",
        "INJ - Hillsboro (Hillsboro Muni)",
        "INK - Wink (Winkler Co)",
        "INL - International Falls (Falls Intl)",
        "INS - Indian Springs (Creech Afb)",
        "INT - Winston-salem (Smith Reynolds)",
        "INW - Winslow (Winslow-Lindbergh Regional Airport)",
        "IOW - Iowa City (Iowa City Municipal Airport)",
        "IPL - Imperial (Imperial Co)",
        "IPT - Williamsport (Williamsport Rgnl)",
        "IRC - Circle (Circle City Airport)",
        "IRK - Kirksville (Kirksville Regional Airport)",
        "ISM - Kissimmee (Kissimmee Gateway Airport)",
        "ISN - Williston (Sloulin Fld Intl)",
        "ISO - Kinston (Kinston Regional Jetport)",
        "ISP - Islip (Long Island Mac Arthur)",
        "ISW - Wisconsin Rapids (Alexander Field South Wood County Airport)",
        "ITH - Ithaca (Ithaca Tompkins Rgnl)",
        "ITO - Hilo (Hilo Intl)",
        "IWD - Ironwood (Gogebic Iron County Airport)",
        "IWS - Houston (West Houston)",
        "IYK - Inyokern (Inyokern Airport)",
        "JAC - Jacksn Hole (Jackson Hole Airport)",
        "JAN - Jackson (Jackson Evers Intl)",
        "JAX - Jacksonville (Jacksonville Intl)",
        "JBR - Jonesboro (Jonesboro Muni)",
        "JCI - Olathe (New Century AirCenter Airport)",
        "JEF - Jefferson City (Jefferson City Memorial Airport)",
        "JES - Jesup (Jesup-Wayne County Airport)",
        "JFK - New York (John F Kennedy Intl)",
        "JGC - Grand Canyon (Grand Canyon Heliport)",
        "JHM - Lahania-kapalua (Kapalua)",
        "JHW - Jamestown (Chautauqua County-Jamestown)",
        "JKA - Gulf Shores (Jack Edwards Airport)",
        "JLN - Joplin (Joplin Rgnl)",
        "JMS - Jamestown (Jamestown Regional Airport)",
        "JNU - Juneau (Juneau Intl)",
        "JOT - Joliet (Regional Airport)",
        "JRA - New York (West 30th St. Heliport)",
        "JRB - New York (Wall Street Heliport)",
        "JST - Johnstown (John Murtha Johnstown-Cambria County Airport)",
        "JVL - Janesville (Southern Wisconsin Regional Airport)",
        "JXN - Jackson (Reynolds Field)",
        "JYL - Sylvania (Plantation Airpark)",
        "JYO - Leesburg (Leesburg Executive Airport)",
        "JZP - Jasper (Pickens County Airport)",
        "K03 - Fort Wainwright (Wainwright As)",
        "KAE - Kake (Kake Seaplane Base)",
        "KAL - Kaltag (Kaltag Airport)",
        "KBC - Brich Creek (Birch Creek Airport)",
        "KBW - Chignik (Chignik Bay Seaplane Base)",
        "KCC - Coffman Cove (Coffman Cove Seaplane Base)",
        "KCL - Chignik Lagoon (Chignik Lagoon Airport)",
        "KCQ - Chignik Lake (Chignik Lake Airport)",
        "KEH - Kenmore (Kenmore Air Harbor Inc Seaplane Base)",
        "KEK - Ekwok (Ekwok Airport)",
        "KFP - False Pass (False Pass Airport)",
        "KGK - Koliganek (Koliganek Airport)",
        "KGX - Grayling (Grayling Airport)",
        "KKA - Koyuk (Koyuk Alfred Adams Airport)",
        "KKB - Kitoi Bay (Kitoi Bay Seaplane Base)",
        "KKH - Kongiganak (Kongiganak Airport)",
        "KLG - Kalskag (Kalskag Airport)",
        "KLL - Levelock (Levelock Airport)",
        "KLN - Larsen Bay (Larsen Bay Airport)",
        "KLS - Kelso (Kelso Longview)",
        "KLW - Klawock (Klawock Airport)",
        "KMO - Manokotak (Manokotak Airport)",
        "KMY - Moser Bay (Moser Bay Seaplane Base)",
        "KNW - New Stuyahok (New Stuyahok Airport)",
        "KOA - Kona (Kona Intl At Keahole)",
        "KOT - Kotlik (Kotlik Airport)",
        "KOY - Olga Bay (Olga Bay Seaplane Base)",
        "KOZ - Ouzinkie (Ouzinkie Airport)",
        "KPB - Point Baker (Point Baker Seaplane Base)",
        "KPC - Port Clarence (Port Clarence Coast Guard Station)",
        "KPN - Kipnuk (Kipnuk Airport)",
        "KPR - Port Williams (Port Williams Seaplane Base)",
        "KPV - Perryville (Perryville Airport)",
        "KPY - Port Bailey (Port Bailey Seaplane Base)",
        "KQA - Akutan (Akutan Seaplane Base)",
        "KSM - St Mary's (St Marys Airport)",
        "KTB - Thorne Bay (Thorne Bay Seaplane Base)",
        "KTN - Ketchikan (Ketchikan Intl)",
        "KTS - Brevig Mission (Brevig Mission Airport)",
        "KUK - Kasigluk (Kasigluk Airport)",
        "KVC - King Cove (King Cove Airport)",
        "KVL - Kivalina (Kivalina Airport)",
        "KWK - Kwigillingok (Kwigillingok Airport)",
        "KWN - Quinhagak (Quinhagak Airport)",
        "KWP - West Point (West Point Village Seaplane Base)",
        "KWT - Kwethluk (Kwethluk Airport)",
        "KYK - Karluk (Karuluk Airport)",
        "KYU - Koyukuk (Koyukuk Airport)",
        "KZB - Zachar Bay (Zachar Bay Seaplane Base)",
        "L06 - Death Valley National Park (Furnace Creek)",
        "L35 - Big Bear (Big Bear City)",
        "LAA - Lamar (Lamar Muni)",
        "LAF - Lafayette (Purude University Airport)",
        "LAL - Lakeland (Lakeland Linder Regional Airport)",
        "LAM - Los Alamos (Los Alamos Airport)",
        "LAN - Lansing (Capital City)",
        "LAR - Laramie (Laramie Regional Airport)",
        "LAS - Las Vegas (Mc Carran Intl)",
        "LAW - Lawton (Lawton-Fort Sill Regional Airport)",
        "LAX - Los Angeles (Los Angeles Intl)",
        "LBB - Lubbock (Lubbock Preston Smith Intl)",
        "LBE - Latrobe (Arnold Palmer Regional Airport)",
        "LBF - North Platte (North Platte Regional Airport Lee Bird Field)",
        "LBL - Liberal (Liberal Muni)",
        "LBT - Lumberton (Municipal Airport)",
        "LCH - Lake Charles (Lake Charles Rgnl)",
        "LCK - Columbus (Rickenbacker Intl)",
        "LCQ - Lake City (Lake City Municipal Airport)",
        "LDJ - Linden (Linden Airport)",
        "LEB - Lebanon (Lebanon Municipal Airport)",
        "LEW - Lewiston (Lewiston Maine)",
        "LEX - Lexington KY (Blue Grass)",
        "LFI - Hampton (Langley Afb)",
        "LFK - Lufkin (Angelina Co)",
        "LFT - Lafayette (Lafayette Rgnl)",
        "LGA - New York (La Guardia)",
        "LGB - Long Beach (Long Beach)",
        "LGC - LaGrange (LaGrange-Callaway Airport)",
        "LGU - Logan (Logan-Cache)",
        "LHD - Anchorage (Lake Hood Seaplane Base)",
        "LHV - Lock Haven (William T. Piper Mem.)",
        "LHX - La Junta (La Junta Muni)",
        "LIH - Lihue (Lihue)",
        "LIT - Little Rock (Adams Fld)",
        "LIV - Livingood (Livingood Airport)",
        "LKE - Seattle (Kenmore Air Harbor Seaplane Base)",
        "LKP - Lake Placid (Lake Placid Airport)",
        "LMT - Klamath Falls (Klamath Falls Airport)",
        "LNA - West Palm Beach (Palm Beach Co Park)",
        "LNK - Lincoln (Lincoln)",
        "LNN - Willoughby (Lost Nation Municipal Airport)",
        "LNR - Lone Rock (Tri-County Regional Airport)",
        "LNS - Lancaster (Lancaster Airport)",
        "LNY - Lanai (Lanai)",
        "LOT - Lockport (Lewis University Airport)",
        "LOU - Louisville (Bowman Fld)",
        "LOZ - London (London-Corbin Airport-MaGee Field)",
        "LPC - Lompoc (Lompoc Airport)",
        "LPR - Lorain-Elyria (Lorain County Regional Airport)",
        "LPS - Lopez (Lopez Island Airport)",
        "LRD - Laredo (Laredo Intl)",
        "LRF - Jacksonville (Little Rock Afb)",
        "LRU - Las Cruces (Las Cruces Intl)",
        "LSE - La Crosse (La Crosse Municipal)",
        "LSF - Fort Benning (Lawson Aaf)",
        "LSV - Las Vegas (Nellis Afb)",
        "LTS - Altus (Altus Afb)",
        "LUF - Phoenix (Luke Afb)",
        "LUK - Cincinnati (Cincinnati Muni Lunken Fld)",
        "LUP - Molokai (Kalaupapa Airport)",
        "LUR - Cape Lisburne (Cape Lisburne Lrrs)",
        "LVK - Livermore (Livermore Municipal)",
        "LVM - Livingston-Montana (Mission Field Airport)",
        "LVS - Las Vegas (Las Vegas Muni)",
        "LWA - South Haven (South Haven Area Regional Airport)",
        "LWB - Lewisburg (Greenbrier Valley Airport)",
        "LWC - Lawrence (Lawrence Municipal)",
        "LWM - Lawrence (Lawrence Municipal Airport)",
        "LWS - Lewiston (Lewiston Nez Perce Co)",
        "LWT - Lewistown (Lewistown Municipal Airport)",
        "LXY - Mexia (Mexia - Limestone County Airport)",
        "LYH - Lynchburg (Lynchburg Regional Preston Glenn Field)",
        "LYU - Ely (Ely Municipal)",
        "LZU - Lawrenceville (Gwinnett County Airport-Briscoe Field)",
        "MAE - Madera (Madera Municipal Airport)",
        "MAF - Midland (Midland Intl)",
        "MBL - Manistee (Manistee County-Blacker Airport)",
        "MBS - Saginaw (Mbs Intl)",
        "MCC - Sacramento (Mc Clellan Afld)",
        "MCD - Mackinac Island (Mackinac Island Airport)",
        "MCE - Merced (Merced Municipal Airport)",
        "MCF - Tampa (Macdill Afb)",
        "MCG - Mcgrath (McGrath Airport)",
        "MCI - Kansas City (Kansas City Intl)",
        "MCK - McCook (McCook Regional Airport)",
        "MCL - McKinley Park (McKinley National Park Airport)",
        "MCN - Macon (Middle Georgia Rgnl)",
        "MCO - Orlando (Orlando Intl)",
        "MCW - Mason City (Mason City Municipal)",
        "MDT - Harrisburg (Harrisburg Intl)",
        "MDW - Chicago (Chicago Midway Intl)",
        "ME5 - Swans Island (Banks Airport)",
        "MEI - Meridian (Key Field)",
        "MEM - Memphis (Memphis Intl)",
        "MER - Merced (Castle)",
        "MFD - Mansfield (Mansfield Lahm Regional)",
        "MFE - Mcallen (Mc Allen Miller Intl)",
        "MFI - Marshfield (Marshfield Municipal Airport)",
        "MFR - Medford (Rogue Valley Intl Medford)",
        "MGC - Michigan City (Michigan City Municipal Airport)",
        "MGE - Marietta (Dobbins Arb)",
        "MGJ - Montgomery (Orange County Airport)",
        "MGM - MONTGOMERY (Montgomery Regional Airport )",
        "MGR - Moultrie (Moultrie Municipal Airport)",
        "MGW - Morgantown (Morgantown Muni Walter L Bill Hart Fld)",
        "MGY - Dayton (Dayton-Wright Brothers Airport)",
        "MHK - Manhattan (Manhattan Reigonal)",
        "MHM - Lake Minchumina (Minchumina Airport)",
        "MHR - Sacramento (Sacramento Mather)",
        "MHT - Manchester NH (Manchester Regional Airport)",
        "MHV - Mojave (Mojave)",
        "MIA - Miami (Miami Intl)",
        "MIB - Minot (Minot Afb)",
        "MIE - Muncie (Delaware County Airport)",
        "MIV - Millville (Millville Muni)",
        "MKC - Kansas City (Downtown)",
        "MKE - Milwaukee (General Mitchell Intl)",
        "MKG - Muskegon (Muskegon County Airport)",
        "MKK - Molokai (Molokai)",
        "MKL - Jackson (Mc Kellar Sipes Rgnl)",
        "MKO - Muskogee (Davis Fld)",
        "MLB - Melbourne (Melbourne Intl)",
        "MLC - Mcalester (Mc Alester Rgnl)",
        "MLD - Malad City (Malad City)",
        "MLI - Moline (Quad City Intl)",
        "MLJ - Milledgeville (Baldwin County Airport)",
        "MLL - Marshall (Marshall Don Hunter Sr. Airport)",
        "MLS - Miles City (Frank Wiley Field)",
        "MLT - Millinocket (Millinocket Muni)",
        "MLU - Monroe (Monroe Rgnl)",
        "MLY - Manley Hot Springs (Manley Hot Springs Airport)",
        "MMH - Mammoth Lakes (Mammoth Yosemite Airport)",
        "MMI - Athens (McMinn Co)",
        "MMU - Morristown (Morristown Municipal Airport)",
        "MMV - Mackminnville (Mc Minnville Muni)",
        "MNM - Macon (Menominee Marinette Twin Co)",
        "MNT - Minto (Minto Airport)",
        "MOB - Mobile (Mobile Rgnl)",
        "MOD - Modesto (Modesto City Co Harry Sham)",
        "MOT - Minot (Minot Intl)",
        "MOU - Mountain Village (Mountain Village Airport)",
        "MPB - Miami (Miami Seaplane Base)",
        "MPI - Mariposa (MariposaYosemite)",
        "MPV - Montpelier (Edward F Knapp State)",
        "MQB - Macomb (Macomb Municipal Airport)",
        "MQT - Marquette (Sawyer International Airport)",
        "MRB - Martinsburg (Eastern WV Regional Airport)",
        "MRI - Anchorage (Merrill Fld)",
        "MRK - Marco Island Airport (Marco Islands)",
        "MRN - Morganton (Foothills Regional Airport)",
        "MRY - Monterey (Monterey Peninsula)",
        "MSL - Muscle Shoals (Northwest Alabama Regional Airport)",
        "MSN - Madison (Dane Co Rgnl Truax Fld)",
        "MSO - Missoula (Missoula Intl)",
        "MSP - Minneapolis (Minneapolis St Paul Intl)",
        "MSS - Massena (Massena Intl Richards Fld)",
        "MSY - New Orleans (Louis Armstrong New Orleans Intl)",
        "MTC - Mount Clemens (Selfridge Angb)",
        "MTH - Marathon (Florida Keys Marathon Airport)",
        "MTJ - Montrose CO (Montrose Regional Airport)",
        "MTM - Metakatla (Metlakatla Seaplane Base)",
        "MUE - Kamuela (Waimea Kohala)",
        "MUI - Muir (Muir Aaf)",
        "MUO - Mountain Home (Mountain Home Afb)",
        "MVL - Morrisville (Morrisville Stowe State Airport)",
        "MVY - Vineyard Haven MA (Martha\\'s Vineyard)",
        "MWA - Marion (Williamson Country Regional Airport)",
        "MWC - Milwaukee (Lawrence J Timmerman Airport)",
        "MWH - Grant County Airport (Grant Co Intl)",
        "MWL - Mineral Wells (Mineral Wells)",
        "MWM - Windom (Windom Municipal Airport)",
        "MXF - Montgomery (Maxwell Afb)",
        "MXY - McCarthy (McCarthy Airport)",
        "MYF - San Diego (Montgomery Field)",
        "MYL - McCall (McCall Municipal Airport)",
        "MYR - Myrtle Beach (Myrtle Beach Intl)",
        "MYU - Mekoryuk (Mekoryuk Airport)",
        "MYV - Yuba City (Yuba County Airport)",
        "N53 - East Stroudsburg (Stroudsburg-Pocono Airport)",
        "N69 - Stormville (Stormville Airport)",
        "N87 - Trenton (Trenton-Robbinsville Airport)",
        "NBG - New Orleans (New Orleans Nas Jrb)",
        "NBU - Glenview (Naval Air Station)",
        "NCN - Chenega (Chenega Bay Airport)",
        "NEL - Lakehurst (Lakehurst Naes)",
        "NFL - Fallon (Fallon Nas)",
        "NGF - Kaneohe Bay (Kaneohe Bay Mcaf)",
        "NGP - Corpus Christi (Corpus Christi NAS)",
        "NGU - Norfolk (Norfolk Ns)",
        "NHK - Patuxent River (Patuxent River Nas)",
        "NIB - Nikolai (Nikolai Airport)",
        "NID - China (China Lake Naws)",
        "NIP - Jacksonville (Jacksonville Nas)",
        "NJK - El Centro (El Centro Naf)",
        "NKT - Cherry Point (Cherry Point Mcas)",
        "NKX - Miramar (Miramar Mcas)",
        "NLC - Lemoore (Lemoore Nas)",
        "NLG - Nelson Lagoon (Nelson Lagoon)",
        "NME - Nightmute (Nightmute Airport)",
        "NMM - Meridian (Meridian Nas)",
        "NNL - Nondalton (Nondalton Airport)",
        "NOW - Port Angeles (Port Angeles Cgas)",
        "NPA - Pensacola (Pensacola Nas)",
        "NPZ - Valparaiso (Porter County Municipal Airport)",
        "NQA - Millington (Millington Rgnl Jetport)",
        "NQI - Kingsville (Kingsville Nas)",
        "NQX - Key West (Key West Nas)",
        "NSE - Milton (Whiting Fld Nas North)",
        "NTD - Point Mugu (Point Mugu Nas)",
        "NTU - Oceana (Oceana Nas)",
        "NUI - Nuiqsut (Nuiqsut Airport)",
        "NUL - Nulato (Nulato Airport)",
        "NUP - Nunapitchuk (Nunapitchuk Airport)",
        "NUQ - Mountain View (Moffett Federal Afld)",
        "NUW - Whidbey Island (Whidbey Island Nas)",
        "NXP - Twenty Nine Palms (Twentynine Palms Eaf)",
        "NXX - Willow Grove (Willow Grove Nas Jrb)",
        "NY9 - Long Lake (Long Lake)",
        "NYC - New York (All Airports)",
        "NYG - Quantico (Quantico Mcaf)",
        "NZC - Jacksonville (Cecil Field)",
        "NZJ - Santa Ana (El Toro)",
        "NZY - San Diego (North Island Nas)",
        "O03 - Morgantown (Morgantown Airport)",
        "O27 - Oakdale (Oakdale Airport)",
        "OAJ - Jacksonville NC (Albert J Ellis)",
        "OAK - Oakland (Metropolitan Oakland Intl)",
        "OAR - Fort Ord (Marina Muni)",
        "OBE - Okeechobee (County)",
        "OBU - Kobuk (Kobuk Airport)",
        "OCA - Ocean Reef Club Airport (Key Largo)",
        "OCF - Ocala (International Airport)",
        "OEB - Coldwater (Branch County Memorial Airport)",
        "OFF - Omaha (Offutt Afb)",
        "OGG - Kahului (Kahului)",
        "OGS - Ogdensburg (Ogdensburg Intl)",
        "OKC - Oklahoma City (Will Rogers World)",
        "OLF - Wolf Point (LM Clayton Airport)",
        "OLH - Old Harbor (Old Harbor Airport)",
        "OLM - Olympia (Olympia Regional Airpor)",
        "OLS - Nogales (Nogales Intl)",
        "OLV - Olive Branch (Olive Branch Muni)",
        "OMA - Omaha (Eppley Afld)",
        "OME - Nome (Nome)",
        "OMN - Ormond Beach (Ormond Beach municipal Airport)",
        "ONH - Oneonta (Oneonta Municipal Airport)",
        "ONP - Newport (Newport Municipal Airport)",
        "ONT - Ontario (Ontario Intl)",
        "OOK - Toksook Bay (Toksook Bay Airport)",
        "OPF - Miami (Opa Locka)",
        "OQU - North Kingstown (Quonset State Airport)",
        "ORD - Chicago (Chicago Ohare Intl)",
        "ORF - Norfolk (Norfolk Intl)",
        "ORH - Worcester (Worcester Regional Airport)",
        "ORI - Port Lions (Port Lions Airport)",
        "ORL - Orlando (Executive)",
        "ORT - Northway (Northway)",
        "ORV - Noorvik (Robert Curtis Memorial Airport)",
        "OSC - Oscoda (Oscoda Wurtsmith)",
        "OSH - Oshkosh (Wittman Regional Airport)",
        "OSU - Columbus (Ohio State University Airport)",
        "OTH - North Bend (Southwest Oregon Regional Airport)",
        "OTS - Anacortes (Anacortes Airport)",
        "OTZ - Kotzebue (Ralph Wien Mem)",
        "OWB - Owensboro (Owensboro Daviess County Airport)",
        "OWD - Norwood (Norwood Memorial Airport)",
        "OXC - Oxford (Waterbury-Oxford Airport)",
        "OXD - Oxford (Miami University Airport)",
        "OXR - Oxnard (Oxnard - Ventura County)",
        "OZA - Ozona (Ozona Muni)",
        "P08 - Cooldige (Coolidge Municipal Airport)",
        "P52 - Cottonwood (Cottonwood Airport)",
        "PAE - Everett (Snohomish Co)",
        "PAH - PADUCAH (Barkley Regional Airport)",
        "PAM - Panama City (Tyndall Afb)",
        "PAO - Palo Alto (Palo Alto Airport of Santa Clara County)",
        "PAQ - Palmer (Palmer Muni)",
        "PBF - Pine Bluff (Grider Fld)",
        "PBG - Plattsburgh (Plattsburgh Intl)",
        "PBI - West Palm Beach (Palm Beach Intl)",
        "PBV - Point Barrow (St George)",
        "PBX - Pikeville (Pike County Airport - Hatcher Field)",
        "PCW - Port Clinton (Erie-Ottawa Regional Airport)",
        "PCZ - Waupaca (Waupaca Municipal Airport)",
        "PDB - Pedro Bay (Pedro Bay Airport)",
        "PDK - Atlanta (Dekalb-Peachtree Airport)",
        "PDT - Pendleton (Eastern Oregon Regional Airport)",
        "PDX - Portland (Portland Intl)",
        "PEC - Pelican (Pelican Seaplane Base)",
        "PEQ - Pecos (Pecos Municipal Airport)",
        "PFN - Panama City (Panama City Bay Co Intl)",
        "PGA - Page (Page Municipal Airport)",
        "PGD - Punta Gorda (Charlotte County-Punta Gorda Airport)",
        "PGV - Greenville (Pitt-Greenville Airport)",
        "PHD - New Philadelpha (Harry Clever Field Airport)",
        "PHF - Newport News (Newport News Williamsburg Intl)",
        "PHK - Pahokee (Pahokee Airport)",
        "PHL - Philadelphia (Philadelphia Intl)",
        "PHN - Port Huron (St Clair Co Intl)",
        "PHO - Point Hope (Point Hope Airport)",
        "PHX - Phoenix (Phoenix Sky Harbor Intl)",
        "PIA - Peoria (Peoria Regional)",
        "PIB - Hattiesburg/Laurel (Hattiesburg Laurel Regional Airport)",
        "PIE - St. Petersburg (St Petersburg Clearwater Intl)",
        "PIH - Pocatello (Pocatello Regional Airport)",
        "PIM - Pine Mountain (Harris County Airport)",
        "PIP - Pilot Point (Pilot Point Airport)",
        "PIR - Pierre (Pierre Regional Airport)",
        "PIT - Pittsburgh (Pittsburgh Intl)",
        "PIZ - Point Lay (Point Lay Lrrs)",
        "PKB - PARKERSBURG (Mid-Ohio Valley Regional Airport)",
        "PLN - Pellston (Pellston Regional Airport of Emmet County Airport)",
        "PMB - Pembina (Pembina Muni)",
        "PMD - Palmdale (Palmdale Rgnl Usaf Plt 42)",
        "PML - Cold Bay (Port Moller Airport)",
        "PMP - Pompano Beach (Pompano Beach Airpark)",
        "PNC - Ponca City (Ponca City Rgnl)",
        "PNE - Philadelphia (Northeast Philadelphia)",
        "PNM - Princeton (Princeton Muni)",
        "PNS - Pensacola (Pensacola Rgnl)",
        "POB - Fort Bragg (Pope Field)",
        "POC - La Verne (Brackett Field)",
        "POE - Fort Polk (Polk Aaf)",
        "POF - Poplar Bluff (Poplar Bluff Municipal Airport)",
        "PPC - Prospect Creek (Prospect Creek Airport)",
        "PPV - Port Protection (Port Protection Seaplane Base)",
        "PQI - Presque Isle (Northern Maine Rgnl At Presque Isle)",
        "PQS - Pilot Station (Pilot Station Airport)",
        "PRC - Prescott (Ernest A Love Fld)",
        "PSC - Pasco (Tri Cities Airport)",
        "PSG - Petersburg (Petersburg James A. Johnson)",
        "PSM - Portsmouth (Pease International Tradeport)",
        "PSP - Palm Springs (Palm Springs Intl)",
        "PSX - Palacios (Palacios Muni)",
        "PTH - Port Heiden (Port Heiden Airport)",
        "PTK - Pontiac (Oakland Co. Intl)",
        "PTU - Port Moller (Platinum)",
        "PUB - Pueblo (Pueblo Memorial)",
        "PUC - Price (Carbon County Regional-Buck Davis Field)",
        "PUW - Pullman (Pullman-Moscow Rgnl)",
        "PVC - Provincetown (Provincetown Muni)",
        "PVD - Providence (Theodore Francis Green State)",
        "PVU - Provo (Provo Municipal Airport)",
        "PWK - Chicago-Wheeling (Chicago Executive)",
        "PWM - Portland (Portland Intl Jetport)",
        "PWT - Bremerton (Bremerton National)",
        "PYM - Plymouth (Plymouth Municipal Airport)",
        "PYP - Centre (Centre-Piedmont-Cherokee County Regional Airport)",
        "R49 - Republic (Ferry County Airport)",
        "RAC - Racine (John H. Batten Airport)",
        "RAL - Riverside (Riverside Muni)",
        "RAP - Rapid City (Rapid City Regional Airport)",
        "RBD - Dallas (Dallas Executive Airport)",
        "RBK - Murrieta-Temecula (French Valley Airport)",
        "RBM - Robinson (Robinson Aaf)",
        "RBN - Fort Jefferson - Dry Tortugas (Fort Jefferson)",
        "RBY - Ruby (Ruby Airport)",
        "RCA - Rapid City (Ellsworth Afb)",
        "RCE - Roche Harbor (Roche Harbor Seaplane Base)",
        "RCZ - Rockingham (Richmond County Airport)",
        "RDD - Redding (Redding Muni)",
        "RDG - Reading (Reading Regional Carl A Spaatz Field)",
        "RDM - Redmond-Bend (Roberts Fld)",
        "RDR - Red River (Grand Forks Afb)",
        "RDU - Raleigh-durham (Raleigh Durham Intl)",
        "RDV - Red Devil (Red Devil Airport)",
        "REI - Redlands (Redlands Municipal Airport)",
        "RFD - Rockford (Chicago Rockford International Airport )",
        "RHI - Rhinelander (Rhinelander Oneida County Airport)",
        "RIC - Richmond (Richmond Intl)",
        "RID - Richmond (Richmond Municipal Airport)",
        "RIF - Richfield (Richfield Minicipal Airport)",
        "RIL - Rifle (Garfield County Regional Airport)",
        "RIR - Riverside (Flabob Airport)",
        "RIU - Rancho Murieta (Rancho Murieta)",
        "RIV - Riverside (March Arb)",
        "RIW - Riverton WY (Riverton Regional)",
        "RKD - Rockland (Knox County Regional Airport)",
        "RKH - Rock Hill (Rock Hill York Co Bryant Airport)",
        "RKP - Rockport (Aransas County Airport)",
        "RKS - Rock Springs (Rock Springs Sweetwater County Airport)",
        "RME - Rome (Griffiss Afld)",
        "RMG - Rome (Richard B Russell Airport)",
        "RMP - Rampart (Rampart Airport)",
        "RMY - Marshall (Brooks Field Airport)",
        "RND - San Antonio (Randolph Afb)",
        "RNM - Ramona (Ramona Airport)",
        "RNO - Reno (Reno Tahoe Intl)",
        "RNT - Renton (Renton)",
        "ROA - Roanoke VA (Roanoke Regional)",
        "ROC - Rochester (Greater Rochester Intl)",
        "ROW - Roswell (Roswell Intl Air Center)",
        "RSH - Russian Mission (Russian Mission Airport)",
        "RSJ - Rosario (Rosario Seaplane Base)",
        "RST - Rochester (Rochester)",
        "RSW - Fort Myers (Southwest Florida Intl)",
        "RUT - Rutland (Rutland State Airport)",
        "RVS - Tulsa (Richard Lloyd Jones Jr Airport)",
        "RWI - Rocky Mount (Rocky Mount Wilson Regional Airport)",
        "RWL - Rawlins (Rawlins Municipal Airport-Harvey Field)",
        "RYY - Atlanta (Cobb County Airport-Mc Collum Field)",
        "S46 - Port O\\'Connor (Port O\\'Connor Airfield)",
        "SAA - SARATOGA (Shively Field Airport)",
        "SAC - Sacramento (Sacramento Executive)",
        "SAF - Santa Fe (Santa Fe Muni)",
        "SAN - San Diego (San Diego Intl)",
        "SAT - San Antonio (San Antonio Intl)",
        "SAV - Savannah (Savannah Hilton Head Intl)",
        "SBA - Santa Barbara (Santa Barbara Muni)",
        "SBD - San Bernardino (San Bernardino International Airport)",
        "SBN - South Bend (South Bend Rgnl)",
        "SBO - Santa Barbara (Emanuel Co)",
        "SBP - San Luis Obispo (San Luis County Regional Airport)",
        "SBS - Steamboat Springs (Steamboat Springs Airport-Bob Adams Field)",
        "SBY - Salisbury (Salisbury Ocean City Wicomico Rgnl)",
        "SCC - Deadhorse (Deadhorse)",
        "SCE - State College Pennsylvania (University Park Airport)",
        "SCH - Scotia NY (Stratton ANGB - Schenectady County Airpor)",
        "SCK - Stockton (Stockton Metropolitan)",
        "SCM - Scammon Bay (Scammon Bay Airport)",
        "SDC - Williamson (Williamson-Sodus Airport)",
        "SDF - Louisville (Louisville International Airport)",
        "SDM - San Diego (Brown Field Municipal Airport)",
        "SDP - Sand Point (Sand Point Airport)",
        "SDX - Sedona (Sedona)",
        "SDY - Sidney (Sidney-Richland Municipal Airport)",
        "SEA - Seattle (Seattle Tacoma Intl)",
        "SEE - El Cajon (Gillespie)",
        "SEF - Sebring (Regional - Hendricks AAF)",
        "SEM - Selma (Craig Fld)",
        "SES - Selma Alabama (Selfield Airport)",
        "SFB - Sanford (Orlando Sanford Intl)",
        "SFF - Spokane (Felts Fld)",
        "SFM - Sanford ME (Sanford Regional)",
        "SFO - San Francisco (San Francisco Intl)",
        "SFZ - Smithfield (North Central State)",
        "SGF - Springfield (Springfield Branson Natl)",
        "SGH - Springfield (Springfield-Beckly Municipal Airport)",
        "SGJ - St. Augustine (St. Augustine Airport)",
        "SGR - Sugar Land (Sugar Land Regional Airport)",
        "SGU - Saint George (St George Muni)",
        "SGY - Skagway (Skagway Airport)",
        "SHD - Weyers Cave (Shenandoah Valley Regional Airport)",
        "SHG - Shungnak (Shungnak Airport)",
        "SHH - Shishmaref (Shishmaref Airport)",
        "SHR - Sheridan (Sheridan County Airport)",
        "SHV - Shreveport (Shreveport Rgnl)",
        "SHX - Shageluk (Shageluk Airport)",
        "SIT - Sitka (Sitka Rocky Gutierrez)",
        "SJC - San Jose (Norman Y Mineta San Jose Intl)",
        "SJT - San Angelo (San Angelo Rgnl Mathis Fld)",
        "SKA - Spokane (Fairchild Afb)",
        "SKF - San Antonio (Lackland Afb Kelly Fld Annex)",
        "SKK - Shaktoolik (Shaktoolik Airport)",
        "SKY - Sandusky (Griffing Sandusky)",
        "SLC - Salt Lake City (Salt Lake City Intl)",
        "SLE - Salem (McNary Field)",
        "SLK - Saranac Lake (Adirondack Regional Airport)",
        "SLN - Salina (Salina Municipal Airport)",
        "SLQ - Sleetmute (Sleetmute Airport)",
        "SMD - Fort Wayne IN (Smith Fld)",
        "SME - Somerset (Lake Cumberland Regional Airport)",
        "SMF - Sacramento (Sacramento Intl)",
        "SMK - St. Michael (St. Michael Airport)",
        "SMN - Salmon (Lemhi County Airport)",
        "SMO - Santa Monica (Santa Monica Municipal Airport)",
        "SMX - Santa Maria (Santa Maria Pub Cpt G Allan Hancock Airport)",
        "SNA - Santa Ana (John Wayne Arpt Orange Co)",
        "SNP - St. Paul Island (St Paul Island)",
        "SNY - Sidney (Sidney Muni Airport)",
        "SOP - Pinehurst-Southern Pines (Moore County Airport)",
        "SOW - Show Low (Show Low Regional Airport)",
        "SPB - San Luis (Scappoose Industrial Airpark)",
        "SPF - Spearfish-South Dakota (Black Hills Airport-Clyde Ice Field)",
        "SPG - St. Petersburg (Albert Whitted)",
        "SPI - Springfield (Abraham Lincoln Capital)",
        "SPS - Wichita Falls (Sheppard Afb Wichita Falls Muni)",
        "SPW - Spencer (Spencer Muni)",
        "SPZ - Silver Springs (Silver Springs Airport)",
        "SQL - San Carlos (San Carlos Airport)",
        "SRQ - Sarasota (Sarasota Bradenton Intl)",
        "SRR - Ruidoso (Sierra Blanca Regional Airport)",
        "SRV - Stony River (Stony River 2 Airport)",
        "SSC - Sumter (Shaw Afb)",
        "SSI - Brunswick (McKinnon Airport)",
        "STC - Saint Cloud (Saint Cloud Regional Airport)",
        "STE - Stevens Point (Stevens Point Municipal Airport)",
        "STG - St. George (St. George Airport)",
        "STJ - Rosecrans (Rosecrans Mem)",
        "STK - Sterling (Sterling Municipal Airport)",
        "STL - St. Louis (Lambert St Louis Intl)",
        "STS - Santa Rosa (Charles M Schulz Sonoma Co)",
        "SUA - Stuart (Witham Field Airport)",
        "SUE - Sturgeon Bay (Door County Cherryland Airport)",
        "SUN - Hailey (Friedman Mem)",
        "SUS - Null (Spirit Of St Louis)",
        "SUU - Fairfield (Travis Afb)",
        "SUX - Sioux City (Sioux Gateway Col Bud Day Fld)",
        "SVA - Savoonga (Savoonga Airport)",
        "SVC - Silver City (Grant County Airport)",
        "SVH - Statesville (Regional Airport)",
        "SVN - Hunter Aaf (Hunter Aaf)",
        "SVW - Sparrevohn (Sparrevohn Lrrs)",
        "SWD - Seward (Seward Airport)",
        "SWF - Newburgh (Stewart Intl)",
        "SXP - Nunam Iqua (Sheldon Point Airport)",
        "SXQ - Soldotna (Soldotna Airport)",
        "SYA - Shemya (Eareckson As)",
        "SYB - Seal Bay (Seal Bay Seaplane Base)",
        "SYR - Syracuse (Syracuse Hancock Intl)",
        "SZL - Knobnoster (Whiteman Afb)",
        "TAL - Tanana (Tanana Airport)",
        "TAN - Taunton (Taunton Municipal Airport - King Field)",
        "TBN - Fort Leonardwood (Waynesville Rgnl Arpt At Forney Fld)",
        "TCC - Tucumcari (Tucumcari Muni)",
        "TCL - Tuscaloosa AL (Tuscaloosa Rgnl)",
        "TCM - Tacoma (Mc Chord Afb)",
        "TCS - Truth Or Consequences (Truth Or Consequences Muni)",
        "TCT - Takotna (Takotna Airport)",
        "TEB - Teterboro (Teterboro)",
        "TEK - Tatitlek (Tatitlek Airport)",
        "TEX - Telluride (Telluride)",
        "TIK - Oklahoma City (Tinker Afb)",
        "TIW - Tacoma (Tacoma Narrows Airport)",
        "TKA - Talkeetna (Talkeetna)",
        "TKE - Tenakee Springs (Tenakee Seaplane Base)",
        "TKF - Truckee (Truckee-Tahoe Airport)",
        "TKI - DALLAS (Collin County Regional Airport at Mc Kinney)",
        "TLA - Teller (Teller Airport)",
        "TLH - Tallahassee (Tallahassee Rgnl)",
        "TLJ - Tatalina (Tatalina Lrrs)",
        "TLT - Tuluksak (Tuluksak Airport)",
        "TMA - Tifton (Henry Tift Myers Airport)",
        "TMB - Kendall-tamiami (Kendall Tamiami Executive)",
        "TNC - Tin City (Tin City LRRS Airport)",
        "TNK - Tununak (Tununak Airport)",
        "TNT - Miami (Dade Collier Training And Transition)",
        "TNX - Tonopah (Tonopah Test Range)",
        "TOA - Torrance (Zamperini Field Airport)",
        "TOC - Toccoa (Toccoa RG Letourneau Field Airport)",
        "TOG - Togiak Village (Togiak Airport)",
        "TOL - Toledo (Toledo)",
        "TOP - Topeka (Philip Billard Muni)",
        "TPA - Tampa (Tampa Intl)",
        "TPL - Temple (Draughon Miller Central Texas Rgnl)",
        "TRI - BRISTOL (Tri-Cities Regional Airport)",
        "TRM - Palm Springs (Jacqueline Cochran Regional Airport)",
        "TSS - New York (East 34th Street Heliport)",
        "TTD - Troutdale (Portland Troutdale)",
        "TTN - Trenton (Trenton Mercer)",
        "TUL - Tulsa (Tulsa Intl)",
        "TUP - Tupelo (Tupelo Regional Airport)",
        "TUS - Tucson (Tucson Intl)",
        "TVC - Traverse City (Cherry Capital Airport)",
        "TVF - Thief River Falls (Thief River Falls)",
        "TVI - Thomasville (Thomasville Regional Airport)",
        "TVL - South Lake Tahoe (Lake Tahoe Airport)",
        "TWA - Twin Hills (Twin Hills Airport)",
        "TWD - Port Townsend (Jefferson County Intl)",
        "TWF - Twin Falls (Magic Valley Regional Airport)",
        "TXK - Texarkana (Texarkana Rgnl Webb Fld)",
        "TYE - Tyonek (Tyonek Airport)",
        "TYR - Tyler (Tyler Pounds Rgnl)",
        "TYS - Knoxville (Mc Ghee Tyson)",
        "U76 - Mountain Home (Mountain Home Municipal Airport)",
        "UDD - Palm Springs (Bermuda Dunes Airport)",
        "UDG - Darlington (Darlington County Jetport)",
        "UES - Waukesha (Waukesha County Airport)",
        "UGN - Chicago (Waukegan Rgnl)",
        "UIN - Quincy (Quincy Regional Baldwin Field)",
        "UMP - Indianapolis (Indianapolis Metropolitan Airport)",
        "UNK - Unalakleet (Unalakleet Airport)",
        "UPP - Opolu (Upolu)",
        "UST - St. Augustine Airport (St. Augustine Airport)",
        "UTM - Tunica (Tunica Municipal Airport)",
        "UTO - Indian Mountains (Indian Mountain Lrrs)",
        "UUK - Kuparuk (Ugnu-Kuparuk Airport)",
        "UUU - Newport RI (Newport State)",
        "UVA - Uvalde (Garner Field)",
        "VAD - Valdosta (Moody Afb)",
        "VAK - Chevak (Chevak Airport)",
        "VAY - Mount Holly (South Jersey Regional Airport)",
        "VBG - Lompoc (Vandenberg Afb)",
        "VCT - Victoria (Victoria Regional Airport)",
        "VCV - Victorville (Southern California Logistics)",
        "VDF - Tampa (Tampa Executive Airport)",
        "VDZ - Valdez (Valdez Pioneer Fld)",
        "VEE - Venetie (Venetie Airport)",
        "VEL - Vernal (Vernal Regional Airport)",
        "VGT - Las Vegas (North Las Vegas Airport)",
        "VIS - Visalia (Visalia Municipal Airport)",
        "VLD - Valdosta (Valdosta Regional Airport)",
        "VNW - Van Wert (Van Wert County Airport)",
        "VNY - Van Nuys (Van Nuys)",
        "VOK - Camp Douglas (Volk Fld)",
        "VPC - Cartersville (Cartersville Airport)",
        "VPS - Valparaiso (Eglin Afb)",
        "VRB - Vero Beach (Vero Beach Muni)",
        "VSF - Springfield VT (Hartness State)",
        "VYS - Peru (Illinois Valley Regional)",
        "W13 - Waynesboro (Eagle's Nest Airport)",
        "WAA - Wales (Wales Airport)",
        "WAL - Wallops Island (Wallops Flight Facility)",
        "WAS - Washington (All Airports)",
        "WBB - Stebbins (Stebbins Airport)",
        "WBQ - Beaver (Beaver Airport)",
        "WBU - Boulder (Boulder Municipal)",
        "WBW - Wilkes-Barre (Wilkes-Barre Wyoming Valley Airport)",
        "WDR - Winder (Barrow County Airport)",
        "WFB - Ketchikan (Ketchikan harbor Seaplane Base)",
        "WFK - Frenchville (Northern Aroostook Regional Airport)",
        "WHD - Hyder (Hyder Seaplane Base)",
        "WHP - Los Angeles (Whiteman Airport)",
        "WIH - Wishram (Wishram Amtrak Station)",
        "WKK - Aleknagik (Aleknagik Airport)",
        "WKL - Waikoloa Village (Waikoloa Heliport)",
        "WLK - Selawik (Selawik Airport)",
        "WMO - White Mountain (White Mountain Airport)",
        "WRB - Macon (Robins Afb)",
        "WRG - Wrangell (Wrangell Airport)",
        "WRI - Wrightstown (Mc Guire Afb)",
        "WRL - Worland (Worland Municipal Airport)",
        "WSD - White Sands (Condron Aaf)",
        "WSJ - San Juan (San Juan - Uganik Seaplane Base)",
        "WSN - South Naknek (South Naknek Airport)",
        "WST - Washington County (Westerly State Airport)",
        "WSX - Westsound (Westsound Seaplane Base)",
        "WTK - Noatak (Noatak Airport)",
        "WTL - Tuntutuliak (Tuntutuliak Airport)",
        "WWD - Wildwood (Cape May Co)",
        "WWP - North Whale Pass (North Whale Seaplane Base)",
        "WWT - Newtok (Newtok Airport)",
        "WYS - West Yellowstone (Yellowstone Airport)",
        "X01 - Everglades (Everglades Airpark)",
        "X07 - Lake Wales (Lake Wales Municipal Airport)",
        "X21 - Titusville (Arthur Dunn Airpark)",
        "X39 - Tampa (Tampa North Aero Park)",
        "X49 - Lakeland (South Lakeland Airport)",
        "XFL - Flagler (Flagler County Airport)",
        "XNA - Bentonville (NW Arkansas Regional)",
        "XZK - Amherst MA (Amherst Amtrak Station AMM)",
        "Y51 - Viroqua (Municipal Airport)",
        "Y72 - Tomah (Bloyer Field)",
        "YAK - Yakutat (Yakutat)",
        "YIP - Detroit (Willow Run)",
        "YKM - Yakima (Yakima Air Terminal McAllister Field)",
        "YKN - Yankton (Chan Gurney)",
        "YNG - Youngstown (Youngstown Warren Rgnl)",
        "YUM - Yuma (Yuma Mcas Yuma Intl)",
        "Z84 - Clear Mews (Clear)",
        "ZBP - Baltimore (Penn Station)",
        "ZFV - Philadelphia (Philadelphia 30th St Station)",
        "ZPH - Zephyrhills (Municipal Airport)",
        "ZRA - Atlantic City NJ (Atlantic City Rail Terminal)",
        "ZRD - Richmond (Train Station)",
        "ZRP - Newark (Newark Penn Station)",
        "ZRT - Hartford (Hartford Union Station)",
        "ZSF - Springfield MA (Springfield Amtrak Station)",
        "ZSY - Scottsdale (Scottsdale Airport)",
        "ZTF - Stamford (Stamford Amtrak Station)",
        "ZUN - Zuni Pueblo (Black Rock)",
        "ZVE - New Haven (New Haven Rail Station)",
        "ZWU - Washington (Washington Union Station)",
        "ZYP - New York (Penn Station)"
    ];
    
    
    $( "#ap1" ).autocomplete({
        source: availableAirports
    });
    $( "#ap2" ).autocomplete({
        source: availableAirports
    });

});
